### ISSUE TITLE
[Question] Replace AsyncIterableIterator with rxjs-based approach

### ISSUE THREAD

**Issue by Lonli-Lokli** [felangel/bloc.js#19]
Thanks for your package, trying to adopt BLoC idea for the angular and find your implementation very helpful!
I have a question/proposal
1) Have you considered making mapEventToStream not async-based but rxjs aka Observable-based?
Sometimes there are situations when you would like to cancel some state changes and switch to the new one (eg what switchMap doing)

Also an Angular has async pipe for subscribing and fetching the data from stream so state property in BLoC can be also /or published as stateSubject.asObservable() instead of state subject.value

2) https://github.com/felangel/bloc.js/blob/master/packages/bloc/lib/src/bloc.ts#L82 lacks unsubscribe, not sure about memory leaks for that.

3) What are the possibility to raise a new event when it comes outside of the component and BLoC? Eg I have a button with AsOfDate on top of my screen and have a list of items, each of them has its own bloc. Basically I would like to handle button click in TopComponent, send AsOfDateClickedEvent to TopComponentBloc and immediately catch this event in ListItemsBloc to fetch the data from server and pass it via Observable<state> to the ListItemsComponent.
Blocs should not know about each other, they should operate via some bus I think.

**Comment by Lonli-Lokli** [comment]
@felangel if you are interested I can share my approach with extending base Bloc and introducing LinkBloc which can be used to solve my 3) point. I've integrated it into my Angular (not AngularDart) sample.

**Comment by felangel** [comment]
Hi @Lonli-Lokli 👋 
Thanks for opening an issue!

I've attempted to address all of these concerns as part of #28 👍 

Closing for now but feel free to reopen if you have additional comments/questions 😄

**Comment by Lonli-Lokli** [comment]
@felangel thanks for the changes, they looks very good!
My 2cents:
1) I also not understand how can we integrate external events 8ntonbloc, as eventSubject is the only source for events.
2) I faced some issues with static fields approach while testing with Jest - it appears that this static field is shared so if we need to assign smth local we will see different results during parallel runs.
