### ISSUE TITLE
package.json for react-bloc package has the wrong typings path

### ISSUE THREAD

**Issue by prateek14** [felangel/bloc.js#21]
package.json for react-bloc package has the wrong typings path

https://github.com/felangel/bloc.js/blob/master/packages/react-bloc/package.json Ln 16
`  "typings": "dist/types/react-bloc.d.ts",` should be `  "typings": "dist/types/lib/react-bloc.d.ts",`

**Comment by felangel** [comment]
Hi @prateek14 👋 
Thanks for opening an issue!

What makes you say the typings path is wrong? I took a look and it seems the current typings location is correct (at least from what I can tell).

![Screen Shot 2020-09-03 at 11 00 00 AM](https://user-images.githubusercontent.com/8855632/92138939-a973a700-edd4-11ea-804c-86fe700817d2.png)

`dist/types/react-bloc.d.ts` looks correct. Let me know what you think?

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional information and I'm happy to continue the conversation 👍

**Comment by prateek14** [comment]
Thanks for the quick reply.
It looks like yarn had installed v0.1.0, issue is fixed on the latest version.
