### ISSUE TITLE
[Question] How to proper test bloc.js

### ISSUE THREAD

**Issue by Lonli-Lokli** [felangel/bloc.js#31]
As a continuation of previous issue, There some async blocs.

What are the possible ways to write verification tests that with the given initial state and input event I will get known number of output states, ended with some specific one?

**Comment by felangel** [comment]
Hi @Lonli-Lokli 👋 
Thanks for opening an issue!

You can check out the bloc tests at https://github.com/felangel/bloc.js/blob/89807106ff3b8fc83fd5db3810f5d13a7118ffc4/packages/bloc/test/bloc.test.ts#L75 for an example. Let me know if that helps 👍

**Comment by Lonli-Lokli** [comment]
Thanks! So with your proposal it's required to complete the bloc stream.

**Comment by felangel** [comment]
@Lonli-Lokli yup so that you know for sure that no more states are emitted 👍
