### ISSUE TITLE
What's the roadmap?

### ISSUE THREAD

**Issue by George-Spanos** [felangel/bloc.js#85]
Hey @felangel ! First of all I wanna say a big **thanks** for the bloc implementation for Dart. I've been doing some of my apps in flutter lately and man your BloC is amazing to work with. 

I am currently working on creating a state machine for machine for another one of my projects and wondered if it makes sense to use BloC for (plain) typescript as well, this is why I stumbled upon this project. It seems though that BloC for typescript is not a thing that has people convinced of it's value yet.

So my questions are:

1. Given that this bloc implementation is already pretty of rigid (from my humble understanding at least), are there plans for major versions right now?
2. And lastly, imagining that dart bloc takes most of your time in terms of maintaining and updating, what could we do to help? :)

Again big thanks for this amazing package.

**Comment by felangel** [comment]
Hi @George-Spanos 👋
Thanks so much for opening an issue and for the support! 💙

1. I have some wip that I need to finish on bloc.js to get it up to speed with the dart version (migrating to the v8 API and including cubit). I’ve been meaning to wrap it up for a while but if it’s something that would be beneficial for you I can try to prioritize it in the coming week.

2. I’m more than happy to discuss any improvements/updates and review corresponding pull requests 👍

**Comment by George-Spanos** [comment]
Since I consider what I want to say more of a personal opinion/suggestions as you mentioned, I will close this issue and transfer this discussion privately. Thanks for your immediate answer!
